---
title: Diagrama de Classes - App Cuida+ (Alinhado aos RFs)
---
classDiagram
    direction LR

    class Usuario {
        -idUsuario
        -nome
    }

    class Medicamento {
        -idMedicamento
        -nome
        -dosagem
        -dataInicio
        -dataFim
        -observacoes 
        -caminhoImagem 
        +salvar() 
        +excluir() 
        +listarTodos()
        +validarCampos() 
    }

    class Horario {
        -idHorario
        -hora: string
    }

    class HistoricoDose {
        -idHistorico
        -dataHoraTomada: datetime
        +marcarComoTomada()
    }

    class Notificacao {
        -idNotificacao
        -mensagem: string
        -dataHoraAgendada: datetime
        +agendar()
        +cancelar()
    }

    Usuario "1" -- "0..*" Medicamento : 
    Medicamento "1" -- "1..*" Horario : 
    Medicamento "1" -- "0..*" HistoricoDose :  
    Horario -- Notificacao :  