---
title: Diagrama de Caso de Uso - App de Gerenciamento de Medicamentos
---
flowchart LR
 subgraph subGraph0["Gerenciar Medicamentos"]
  direction TB
   UC1("Cadastrar Medicamento")
   UC2("Consultar Medicamentos")
   UC3("Editar Medicamento")
   UC4("Excluir Medicamento")
 end
 subgraph subGraph1["Funções de Suporte"]
  direction TB
   S1("Validar Campos")
   S2("Adicionar Observações")
   S3("Adicionar Imagem")
 end
 subgraph subGraph2["Módulos Adicionais"]
  direction TB
   M1("Consultar Calendário")
   M2("Notificar Medicamento")
 end
 subgraph subGraph3["Sistema Cuida+"]
    subGraph0
    subGraph1
    subGraph2
 end
  Usuário["Usuário"] -- "RF01" --> UC1
  Usuário -- "RF04" --> UC2
  Usuário -- "RF03" --> UC3
  Usuário -- "RF08" --> UC4
  Usuário -- "RF09" --> M1
  
  UC1 -. "RF02" .-> S1
  UC1 -. "RF06" .-> S2
  UC1 -. "RF07" .-> S3
  
  UC3 -. "RF02" .-> S1
  UC3 -. "RF06" .-> S2
  UC3 -. "RF07" .-> S3
  
  UC1 -- "RF05" --> M2
  UC3 -- "RF05" --> M2
  UC4 -- "RF05" --> M2
  
  M2 ----> Notifier["Sistema de Notificações"]